<?php

$queries = array(
    'http://lod2.eu/Query/Testimonials',
    'http://lod2.eu/Query/Demos',
    'http://lod2.eu/Query/Webinars'
);

$querUri          = $queries[time() % count($queries)];
$queryInstance    = new OntoWiki_Resource($querUri, OntoWiki::getInstance()->selectedModel);
$queryDescription = $queryInstance->getDescription();
$queryDescription = $queryDescription[$querUri];

$content = '';
if (isset($queryDescription['http://ns.ontowiki.net/SysOnt/sparql_code'][0]['value'])) {
    $sparqlCode = $queryDescription['http://ns.ontowiki.net/SysOnt/sparql_code'][0]['value'];
    $content    = $this->querylist($sparqlCode, 'lod2/item.phtml', array('options' => array('show_link' => true)));
}

$title = $queryInstance->getTitle();
if (empty($title)) {
    $title = 'Query Result';
}

?>
<div class="section random-results">
    <script type="text/javascript">
    $(document).ready(function () {
        if ($.browser.webkit && document.readyState != 'complete') {
            setTimeout(arguments.callee, 10);
            return;
        }
<?php if ($querUri != 'http://lod2.eu/Query/Webinars'): ?>
        var results = $('.random-results').find('.result').cycle();
<?php else: ?>
        $('.random-results .result').hide();
        var randomSize = $('.random-results .result').size(),
            randomIndex = Math.floor(Math.random() * randomSize);
console.log(randomSize);
console.log(randomIndex);
        $('.random-results .result').eq(randomIndex).show();
<?php endif; ?>
    });
    </script>
    <h3><?php echo $title ?></h3>
    <div class="section-content">
        <?php echo $content; ?>
    </div>
</div>

