<?php
// this is the standard template data
$templateData = array(
    'title' => $this->title,
    'resourceUri' => $this->resourceUri,
    'description' => $this->description,
    'descriptionHelper' => $this->descriptionHelper,
);
?>

<?php if ($content = trim($this->partial('lod2/content.phtml', $templateData))): ?>

<div class="maincontent">
    <div class="section">
        <h3><?php echo $this->title ?></h3>
            <?php if (isset($this->description['http://lod2.eu/schema/partner'][0]['value'])) {
                $partnerResourceUri = $this->description['http://lod2.eu/schema/partner'][0]['value'];
                $partnerResource = new OntoWiki_Resource($partnerResourceUri, OntoWiki::getInstance()->selectedModel);
                // echo $partnerResource->getTitle();
                // TODO: Partner Liste in inline table
            }
            ?>
        <div class="section-content">
            <?php echo $content; ?>
            
            <?php if (isset($this->description['http://usefulinc.com/ns/doap#homepage'][0]['value'])): ?><div>Homepage: <a href="<?php 
                echo $this->description['http://usefulinc.com/ns/doap#homepage'][0]['value'] ?>"><?php 
                echo $this->description['http://usefulinc.com/ns/doap#homepage'][0]['value'] 
            ?></a></div><?php endif; ?>
            
            <?php if (isset($this->description['http://lod2.eu/schema/partner'])): ?><div>Partner: <?php 
                echo $this->objectlist($this->description['http://lod2.eu/schema/partner'], $this->descriptionHelper); 
            ?></div><?php endif; ?>
        </div>
    </div>
</div>

<?php endif; ?>


<?php // Webinars

$query = <<<EOT
PREFIX lod2: <http://lod2.eu/schema/>
PREFIX sysont: <http://ns.ontowiki.net/SysOnt/>
SELECT DISTINCT ?resourceUri
WHERE {
    ?resourceUri lod2:project <{$this->resourceUri}> .
    ?resourceUri a lod2:Webinar .
    OPTIONAL {
        ?resourceUri sysont:order ?order.
    }
    FILTER (!isBLANK(?resourceUri))
}
ORDER BY ASC(?order)
EOT;

$webinars = trim($this->querylist($query, 'lod2/items/li.phtml'));

?>

<?php if ($webinars): ?>
<div class="subcolumns">
    <?php if ($webinars): ?>
    <div class="c50l">
        <div class="subcl widget-deeplink">
            <h3>Webinars</h3>
             <ul>
                <?php echo $webinars; ?>
             </ul>
        </div>
    </div>
    <?php endif; ?>
</div>
<?php endif; ?>
