<?php

$templateData = array(
    'title'             => $this->title,
    'resourceUri'       => $this->resourceUri,
    'description'       => $this->description,
    'descriptionHelper' => $this->descriptionHelper,
);

$embed = isset($this->description['http://lod2.eu/schema/embedURL'][0]['value'])
         ? $this->description['http://lod2.eu/schema/embedURL'][0]['value']
         : null;

?>
<div class="maincontent">
    <div class="section webinar">
        <h3><a href="<?php echo $this->url($this->resourceUri); ?>"><?php echo $this->title; ?></a></h3>
        <div class="section-content">
            <?php echo $this->partial('lod2/content.phtml', $templateData); ?>
            <?php if ($embed): ?>
                <iframe width="500" height="375" src="<?php echo $embed; ?>" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
            <?php endif; ?>
        </div>
    </div>
</div>

