<div class="hero-unit">
    <h1><?= $this->title ?></h1>
    <p></p>
</div>

<!-- Example row of columns for a Feed -->
<div class="row">
    <div class="span4">
        <h2>Feed Item 1</h2>
        <p>This is the text of the first item in the feed</p>
        <p><a class="btn" href="#">View details &raquo;</a></p>
    </div>

    <div class="span4">
        <h2>Feed Item 2</h2>
        <p>This is the text of the second item in the feed</p>
        <p><a class="btn" href="#">View details &raquo;</a></p>
    </div>

    <div class="span4">
        <h2>Feed Item 3</h2>
        <p>This is the text of the second item in the feed</p>
        <p><a class="btn" href="#">View details &raquo;</a></p>
    </div>
</div>
