<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2012, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org feed template
 *
 * arranges the news feed for the resource
 */

// prepare module options
$moduleConfig = new Zend_Config(array());
$content = trim($this->module('map', $moduleConfig));
?>
<h1>Map</h1>
<?php if (!empty($content)): ?>
<?php echo $content; ?>
<?php endif; ?>
